spring:
  jpa:
    hibernate.ddl-auto: create
    show-sql: true
  datasource:
    data: classpath:data.sql
    initialization-mode: always
  profiles:
    active:
      - dev

---
#All configs below OVERRIDE the default's configs, not REPLACE the whole default. 
#The rest of default's configs (which not overriden) still remain active
spring:
  profiles: dev
  
#  h2:
#    console:
#      enabled: true
#  datasource:
#    url: jdbc:h2:mem:testdb
    
  datasource:
    url: jdbc:sqlserver://DESKTOP-05JDR01\\SQLEXPRESS:1433;databaseName=ecommerce
    username: sa1
    password: 123456
  jpa:
    database-platform: org.hibernate.dialect.SQLServer2012Dialect
